[ROCm] Fixed issue with Failed to launch ROCm kernel.
ROCm/xla pull request #61
Opened 2024-10-30 23:47 UTC by zoranjovanovic-ns

2024-10-31 01:15 UTC, Ruturaj4 approved these changes
LGTM

2024-11-05 16:22 UTC, pemeliya requested changes

2024-11-05 16:22 UTC, pemeliya commented on xla/service/gpu/buffer_comparator.cu.cc
> +  int idx = (threadIdx.x + blockIdx.x * blockDim.x) * unroll;
To be on the safe side, I think we should make idx to be uint64_t ?

2024-11-05 16:22 UTC, pemeliya commented on xla/service/gpu/buffer_comparator.cu.cc
> +      if (isnan(elem_a) && isnan(elem_b)) return;
Shall we use continue here instead of return ? And in all other kernels too ?

2024-11-05 17:02 UTC, zoranjovanovic-ns commented on xla/service/gpu/buffer_comparator.cu.cc
> +      if (isnan(elem_a) && isnan(elem_b)) return;
Yes, thank you.

2024-11-05 17:32 UTC, pemeliya requested changes

2024-11-05 17:32 UTC, pemeliya commented on xla/service/gpu/buffer_comparator.cu.cc
> +  int idx = (threadIdx.x + blockIdx.x * blockDim.x) * unroll;
Can you please change the type of 'idx' and 'unroll' to uint64_t for all kernels ? 
I am just afraid of that the compiler will first calculate the product 'threadIdx.x + blockIdx.x * blockDim.x) * unroll' using int32 arithmetic and then cast it to uint64_t ...

2024-11-06 07:36 UTC, pemeliya approved these changes

2024-11-06 11:57 UTC, merged